### ISSUE TITLE
quick town setup command?

### ISSUE THREAD

**Issue by lilserf** [lilserf/botc_mover#31]
When run from the control channel, it would infer as much as possible via naming/regexes:
- assume the control channel is in the Day category
- assume the night category is "{day} - Night"
- assume the roles are "{day} Storyteller" and "{day} Villager"
- assume the first voice channel in the Day category is Town Square

**Comment by lilserf** [comment]
The problem is that creation requires giving broader permissions to the bot - I don’t know if people would be hesitant to give that level of perms? Probably not

**Comment by magroader** [comment]
When you invite a bot, you are supposed to be able to uncheck permissions you don't want to grant. The bot should then be able to gracefully handle a lack of permissions (for example, by telling you it can't do an operation because it doesn't have permission, please reinvite the bot with that permission).

**Comment by magroader** [comment]
I like how your readme details precisely what it uses each permission for, that seems really nice!

**Comment by magroader** [comment]
I think this is no longer necessary with `!createTown` and `!addTown` available
